### PR TITLE
footer: alphabetize top contributors

### PR DESCRIPTION
**Pull request by BlaineEXE**
Alphabetize the Top Contributors list to not imply favoritism.

Signed-off-by: Blaine Gardner <blaine.gardner@suse.com>

### CODE REVIEW

**Comment by BlaineEXE** [comment]
I'm not sure who to tag here other than @jbw976 and @galexrt. @travisn may have thoughts?

**Comment by iranzo** [comment]
Seems that this needs a rebase

**Comment by galexrt** [comment]
Oh yeah, that needs a rebase. I'll approve then.

**Comment by BlaineEXE** [comment]
updataed @galexrt & @iranzo

**Pull request merged**
