### PR TITLE
Rook site redesign

### PR DESCRIPTION
**Pull request by rathpc**
This PR implements the new Rook site redesign. I have set up a staging site here which will be updated as changes are pushed: https://rathpc.github.io/rook.github.io/ 

~This is a current WIP. Outstanding edits include:~
~- [x] Final Copy~
~- [x] Asciinema recordings for home page~

_Adjustments that have been made that dissect from the original redesign_
- Dropdown menu under *Documentation* in the navigation has been converted to just a static link to the current docs page until a more robust\ re-architecture of the documentation occurs to support a multiple storage provider doc arrangement

**All changes have been made and this is ready for a final PR 💯**

### CODE REVIEW

**Comment by mmack** [comment]
Wow that looks stunning!

**Comment by KellyGriffin** [comment]
Looks awesome...No standouts from an issues perspective.  Really easy to navigate

**Comment by rathpc** [comment]
Hey all, just updated some margins in the index page per design feedback. This applies only to the desktop breakpoints.

Additionally, logic has been added to swap out the **asciinema** sources when clicking through the various storage providers. We will just need to actually update the contents of those files now to represent the correct output examples.

**Comment by rathpc** [comment]
This resolves https://github.com/rook/rook/issues/3058

**Comment by rathpc** [comment]
@jbw976 that is correct

**Comment by rathpc** [comment]
This resolves https://github.com/upbound/upbound/issues/64

**Pull request merged**
